language: bash
sudo: required
services:
  - docker

env:
  matrix:
      - PHP_VERSION=70 BUILD_SERVICE=php-fpm
      - PHP_VERSION=71 BUILD_SERVICE=php-fpm

# Installing a newer Docker version
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - docker version

script: ./travis-build.sh

notifications:
  slack: mhlsoftware:fJKaZkBD8t9wcxQtLV2rGo8x
