version: '3'

services:

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./docker/php-fpm
            args:
                - INSTALL_PGSQL=${APP_INSTALL_PGSQL}
                - INSTALL_PG_CLIENT=${APP_INSTALL_PG_CLIENT}
                - INSTALL_MSSQL=${APP_INSTALL_MSSQL}
                - INSTALL_MYSQLI=${APP_INSTALL_MYSQLI}
                - INSTALL_MEMCACHED=${APP_INSTALL_MEMCACHED}
                - INSTALL_PHPREDIS=${APP_INSTALL_PHPREDIS}
                - INSTALL_MONGO=${APP_INSTALL_MONGO}
                - INSTALL_AEROSPIKE=${APP_INSTALL_AEROSPIKE}
                - INSTALL_AMQP=${APP_INSTALL_AMQP}
                - INSTALL_ZIP_ARCHIVE=${APP_INSTALL_ZIP_ARCHIVE}
                - INSTALL_SOAP=${APP_INSTALL_SOAP}
                - INSTALL_BCMATH=${APP_INSTALL_BCMATH}
                - INSTALL_GMP=${APP_INSTALL_GMP}
                - INSTALL_EXIF=${APP_INSTALL_EXIF}
                - INSTALL_XDEBUG=${APP_INSTALL_XDEBUG}
                - INSTALL_OPCACHE=${APP_INSTALL_OPCACHE}
                - INSTALL_BLACKFIRE=${APP_INSTALL_BLACKFIRE}
                - INSTALL_TOKENIZER=${APP_INSTALL_TOKENIZER}
                - INSTALL_INTL=${APP_INSTALL_INTL}
            dockerfile: "Dockerfile-${PHP_VERSION}"
        volumes:
            - ./:/app
            - ./docker/php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
            - ./docker/php-fpm/${AEROSPIKE_INI_FILE}:/usr/local/etc/php/conf.d/aerospike.ini
            - ./docker/php-fpm/${XDEBUG_INI_FILE}:/usr/local/etc/php/conf.d/xdebug.ini
            - ./docker/php-fpm/${OPCACHE_INI_FILE}:/usr/local/etc/php/conf.d/opcache.ini
        expose:
            - "9000"
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        networks:
            - backend

### Aerospike c Container ###################################

    aerospike:
      build: ./docker/aerospike
      volumes:
        - ${DATA_SAVE_PATH}/aerospike:/opt/aerospike/data
      ports:
        - "${AEROSPIKE_SERVICE_PORT}:3000"
        - "${AEROSPIKE_FABRIC_PORT}:3001"
        - "${AEROSPIKE_HEARTBEAT_PORT}:3002"
        - "${AEROSPIKE_INFO_PORT}:3003"
      networks:
        - backend

### Networks Setup ############################################

networks:
  backend:
    driver: "bridge"
